runtime: nodejs

env_variables:
  # Change this to your defined bucket name
  GCLOUD_STORAGE_BUCKET: bucket-pastes-name

handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto